{
 "title": "Map",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Instances",
    "query": {
     "query": "kong_client{job=\"nas\"}"
    }
   },
   { "name": "MinutesAgo", "query": "5,10,30,60,180" }
  ]
 },
 "panels": [
  {
   "title": "Who",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(kong_client_lastseen{instance=\"$Instances\"})*1000",
     "legendFormat": "{{ target }} {{ place }}"
    }
   ]
  },
  {
   "title": "Kong Service/Route",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(kong_client_lastseen{instance=\"$Instances\"})*1000",
     "legendFormat": "{{ service }}/{{ route }} ({{target}})"
    }
   ]
  },
  {
   "title": "Hits (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kong_client{instance=\"$Instances\"}) by (service, route)) - (sum(kong_client{instance=\"$Instances\"} offset 12h) by (service, route))",
     "legendFormat": "{{ service }} / {{ route }}"
    }
   ]
  },
  {
   "title": "Past X Hours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_client{instance=\"$Instances\", place!~\"GB/Edinburgh.*\"})-sum(kong_client{instance=\"$Instances\", place!~\"GB/Edinburgh.*\"} offset 1h)",
     "legendFormat": "1 Hour"
    },
    {
     "expr": "sum(kong_client{instance=\"$Instances\", place!~\"GB/Edinburgh.*\"})-sum(kong_client{instance=\"$Instances\", place!~\"GB/Edinburgh.*\"} offset 6h)",
     "legendFormat": "6 Hour"
    },
    {
     "expr": "sum(kong_client{instance=\"$Instances\", place!~\"GB/Edinburgh.*\"})-sum(kong_client{instance=\"$Instances\", place!~\"GB/Edinburgh.*\"} offset 12h)",
     "legendFormat": "12 Hour"
    }
   ]
  },
  {
   "title": "$MinutesAgo Minutes Ago",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "valueName": "current",
   "targets": [
    {
     "expr": "(sort_desc( kong_client{instance=\"$Instances\"}))    + on(target) group_left(instance)\n(\n   0 * (time() - kong_client_lastseen{instance=\"$Instances\"} < $MinutesAgo*60)\n)"
    }
   ]
  },
  {
   "title": "$Instances",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "valueName": "current",
   "targets": [
    {
     "expr": "kong_client{job=\"nas\", instance=\"$Instances\", place!~\"GB/Edinburgh.*\"}-(kong_client{job=\"nas\", instance=\"$Instances\", place!~\"GB/Edinburgh.*\"} offset $__rate_interval) > 0"
    }
   ]
  },
  {
   "title": "$Instances (All Time)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "valueName": "current",
   "targets": [
    {
     "expr": "sort(kong_client{job=\"nas\", instance=\"$Instances\", place!~\"GB/Edinburgh.*\"})"
    }
   ]
  }
 ]
}